server:
  port:8088

#eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : usuario-service
          uri: lb://usuario-service
          predicates:
            - Path = /usuario/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path = /moto/**
        - id: auto-service
          uri: lb://auto-service
          predicates:
            - Path = /auto/**



